"""empty message

Revision ID: 836549e4538a
Revises: 
Create Date: 2023-09-25 14:54:21.877544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836549e4538a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('mer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mer_username', sa.String(length=100), nullable=True),
    sa.Column('mer_pwd', sa.String(length=255), nullable=True),
    sa.Column('mer_dateadded', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('mer_id')
    )
    op.create_table('store',
    sa.Column('store_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.String(length=120), nullable=False),
    sa.Column('store_phone', sa.String(length=50), nullable=False),
    sa.Column('store_address', sa.String(length=200), nullable=False),
    sa.Column('store_pic', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('store_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store')
    op.drop_table('merchants')
    # ### end Alembic commands ###
